<?php
/**
 *
 * This file is part of the Ukrainian Language Pack
 * for the phpBB Forum Software.
 *
 * @copyright (c) 2026 Magnum <https://magnumblog.space>
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 * Ukrainian translation by Magnum (magnumblog.space)
 *
 */

/**
 * DO NOT CHANGE
 */
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge($lang, array(
	'HELP_BBCODE_BLOCK_IMAGES'	=> 'Показ зображень у повідомленнях',
	'HELP_BBCODE_BLOCK_INTRO'	=> 'Вступ',
	'HELP_BBCODE_BLOCK_LINKS'	=> 'Створення посилань',
	'HELP_BBCODE_BLOCK_LISTS'	=> 'Створення списків',
	'HELP_BBCODE_BLOCK_OTHERS'	=> 'Інші питання',
	'HELP_BBCODE_BLOCK_QUOTES'	=> 'Цитування та вивід тексту фіксованої ширини',
	'HELP_BBCODE_BLOCK_TEXT'	=> 'Форматування тексту',

	'HELP_BBCODE_IMAGES_ATTACHMENT_ANSWER'	=> 'Вкладення тепер можна розміщувати в будь-якій частині повідомлення за допомогою нового BBCode <strong>[attachment=][/attachment]</strong>, якщо функціонал вкладень увімкнено адміністратором форуму і якщо вам надано відповідні права для створення вкладень. На екрані публікації повідомлення є випадний список (або кнопка) для розміщення вкладень у тексті.',
	'HELP_BBCODE_IMAGES_ATTACHMENT_QUESTION'	=> 'Додавання вкладень до повідомлення',
	'HELP_BBCODE_IMAGES_BASIC_ANSWER'	=> 'BBCode phpBB містить тег для додавання зображень до ваших повідомлень. Дві дуже важливі речі, які варто пам’ятати при використанні цього тегу: по-перше, багатьом користувачам не подобається велика кількість зображень у повідомленнях, а по-друге, зображення, яке ви показуєте, має бути вже доступне в інтернеті (воно не може існувати лише на вашому комп’ютері, звісно, якщо ви не запускаєте власний веб-сервер!). Щоб показати зображення, вам потрібно обгорнути URL-адресу, що вказує на зображення, тегами <strong>[img][/img]</strong>. Наприклад:<br /><br /><strong>[img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/img]</strong><br /><br />Як зазначено в розділі про URL вище, ви можете обгорнути зображення тегом <strong>[url][/url]</strong>, якщо бажаєте, напр.<br /><br /><strong>[url=https://www.phpbb.com/][img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/img][/url]</strong><br /><br />згенерує:<br /><br /><a href="https://www.phpbb.com/"><img src="https://www.phpbb.com/theme/images/logos/blue/160x52.png" alt="" /></a>',
	'HELP_BBCODE_IMAGES_BASIC_QUESTION'	=> 'Додавання зображення до повідомлення',

	'HELP_BBCODE_INTRO_BBCODE_ANSWER'	=> 'BBCode — це особлива реалізація HTML. Чи можете ви фактично використовувати BBCode у своїх повідомленнях на форумі, визначає адміністратор. Крім того, ви можете вимкнути BBCode для окремого повідомлення через форму публікації. Сам BBCode подібний за стилем до HTML: теги обгорнуто квадратними дужками [ і ], а не &lt; і &gt;, і він надає більший контроль над тим, що і як відображається. Залежно від використовуваного шаблону, додавання BBCode до ваших повідомлень може бути значно легшим завдяки клікабельному інтерфейсу над областю повідомлення на формі публікації. Навіть з цим наступний посібник може бути корисним.',
	'HELP_BBCODE_INTRO_BBCODE_QUESTION'	=> 'Що таке BBCode?',

	'HELP_BBCODE_LINKS_BASIC_ANSWER'	=> 'BBCode phpBB підтримує кілька способів створення URI (Уніфікованих ідентифікаторів ресурсів), більш відомих як URL.<ul><li>Перший з них використовує тег <strong>[url=][/url]</strong>, все, що ви введете після знаку =, стане URL-адресою вмісту цього тегу. Наприклад, щоб послатися на phpBB.com, ви могли б використати:<br /><br /><strong>[url=https://www.phpbb.com/]</strong>Відвідайте phpBB!<strong>[/url]</strong><br /><br />Це згенерує наступне посилання: <a href="https://www.phpbb.com/">Відвідайте phpBB!</a> Зверніть увагу, посилання відкривається в тому самому чи новому вікні залежно від налаштувань браузера користувача.</li><li>Якщо ви бажаєте, щоб сама URL-адреса відображалася як посилання, ви можете просто використати:<br /><br /><strong>[url]</strong>https://www.phpbb.com/<strong>[/url]</strong><br /><br />Це згенерує наступне посилання: <a href="https://www.phpbb.com/">https://www.phpbb.com/</a></li><li>Крім того, phpBB має функцію під назвою <i>Магічні посилання</i>, яка перетворить будь-яку синтаксично правильну URL-адресу на посилання без потреби вказувати теги чи навіть початкове http://. Наприклад, набравши www.phpbb.com у своєму повідомленні, ви автоматично отримаєте <a href="http://www.phpbb.com/">www.phpbb.com</a> у виведеному повідомленні.</li><li>Те саме однаково стосується email-адрес — ви можете або явно вказати адресу, наприклад:<br /><br /><strong>[email]</strong>no.one@domain.adr<strong>[/email]</strong><br /><br />що виведе <a href="mailto:no.one@domain.adr">no.one@domain.adr</a>, або просто ввести no.one@domain.adr у своєму повідомленні, і воно буде автоматично перетворене під час перегляду.</li></ul>Як і з усіма тегами BBCode, ви можете обгортати URL-адреси навколо будь-яких інших тегів, таких як <strong>[img][/img]</strong> (див. наступний запис), <strong>[b][/b]</strong> тощо. Як і з тегами форматування, вам потрібно самостійно стежити за правильним порядком відкриття й закриття, наприклад:<br /><br /><strong>[url=https://www.phpbb.com/][img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/url][/img]</strong><br /><br /><span style="text-decoration: underline">не</span> правильний, що може призвести до видалення вашого повідомлення, тому будьте уважні.',
	'HELP_BBCODE_LINKS_BASIC_QUESTION'	=> 'Посилання на інший сайт',

	'HELP_BBCODE_LISTS_ORDERER_ANSWER'	=> 'Другий тип списку, впорядкований список, дає вам контроль над тим, що виводиться перед кожним пунктом. Щоб створити впорядкований список, використовуйте <strong>[list=1][/list]</strong> для нумерованого списку або <strong>[list=a][/list]</strong> для алфавітного списку. Як і для невпорядкованого списку, пункти вказуються за допомогою <strong>[*]</strong>. Наприклад:<br /><br /><strong>[list=1]</strong><br /><strong>[*]</strong>Піти в магазин<br /><strong>[*]</strong>Купити новий комп’ютер<br /><strong>[*]</strong>Вилаяти комп’ютер, коли той зависне<br /><strong>[/list]</strong><br /><br />згенерує наступне:<ol style="list-style-type: decimal;"><li>Піти в магазин</li><li>Купити новий комп’ютер</li><li>Вилаяти комп’ютер, коли той зависне</li></ol>Тоді як для алфавітного списку ви б використали:<br /><br /><strong>[list=a]</strong><br /><strong>[*]</strong>Перша можлива відповідь<br /><strong>[*]</strong>Друга можлива відповідь<br /><strong>[*]</strong>Третя можлива відповідь<br /><strong>[/list]</strong><br /><br />видаючи<ol style="list-style-type: lower-alpha"><li>Перша можлива відповідь</li><li>Друга можлива відповідь</li><li>Третя можлива відповідь</li></ol><br /><strong>[list=A]</strong><br /><strong>[*]</strong>Перша можлива відповідь<br /><strong>[*]</strong>Друга можлива відповідь<br /><strong>[*]</strong>Третя можлива відповідь<br /><strong>[/list]</strong><br /><br />видаючи<ol style="list-style-type: upper-alpha"><li>Перша можлива відповідь</li><li>Друга можлива відповідь</li><li>Третя можлива відповідь</li></ol><br /><strong>[list=i]</strong><br /><strong>[*]</strong>Перша можлива відповідь<br /><strong>[*]</strong>Друга можлива відповідь<br /><strong>[*]</strong>Третя можлива відповідь<br /><strong>[/list]</strong><br /><br />видаючи<ol style="list-style-type: lower-roman"><li>Перша можлива відповідь</li><li>Друга можлива відповідь</li><li>Третя можлива відповідь</li></ol><br /><strong>[list=I]</strong><br /><strong>[*]</strong>Перша можлива відповідь<br /><strong>[*]</strong>Друга можлива відповідь<br /><strong>[*]</strong>Третя можлива відповідь<br /><strong>[/list]</strong><br /><br />видаючи<ol style="list-style-type: upper-roman"><li>Перша можлива відповідь</li><li>Друга можлива відповідь</li><li>Третя можлива відповідь</li></ol>',
	'HELP_BBCODE_LISTS_ORDERER_QUESTION'	=> 'Створення впорядкованого списку',
	'HELP_BBCODE_LISTS_UNORDERER_ANSWER'	=> 'BBCode підтримує два типи списків: невпорядкований і впорядкований. За суттю вони такі самі, як і їхні HTML-еквіваленти. Невпорядкований список виводить кожен пункт вашого списку послідовно один за одним, відступаючи кожен маркером. Щоб створити невпорядкований список, використовуйте <strong>[list][/list]</strong> і визначайте кожен пункт списку за допомогою <strong>[*]</strong>. Наприклад, щоб перерахувати ваші улюблені кольори, ви могли б використати:<br /><br /><strong>[list]</strong><br /><strong>[*]</strong>Червоний<br /><strong>[*]</strong>Синій<br /><strong>[*]</strong>Жовтий<br /><strong>[/list]</strong><br /><br />Це згенерує наступний список:<ul><li>Червоний</li><li>Синій</li><li>Жовтий</li></ul><br />Крім того, ви можете вказати стиль маркера списку за допомогою <strong>[list=disc][/list]</strong>, <strong>[list=circle][/list]</strong> або <strong>[list=square][/list]</strong>.',
	'HELP_BBCODE_LISTS_UNORDERER_QUESTION'	=> 'Створення невпорядкованого списку',

	'HELP_BBCODE_OTHERS_CUSTOM_ANSWER'	=> 'Якщо ви є адміністратором цього форуму та маєте відповідні права, ви можете додавати додаткові BBCode через розділ користувацьких BBCode.',
	'HELP_BBCODE_OTHERS_CUSTOM_QUESTION'	=> 'Чи можу я додати власні теги?',

	'HELP_BBCODE_QUOTES_CODE_ANSWER'	=> 'Якщо ви бажаєте вивести фрагмент коду або будь-що інше, що потребує фіксованої ширини, напр. шрифт типу Courier, вам слід обгорнути текст тегами <strong>[code][/code]</strong>, напр.<br /><br /><strong>[code]</strong>echo &quot;Це якийсь код&quot;;<strong>[/code]</strong><br /><br />Все форматування, використане в тегах <strong>[code][/code]</strong>, зберігається при подальшому перегляді.',
	'HELP_BBCODE_QUOTES_CODE_QUESTION'	=> 'Вивід коду або даних фіксованої ширини',
	'HELP_BBCODE_QUOTES_TEXT_ANSWER'	=> 'Є два способи цитування тексту: з посиланням на джерело або без нього.<ul><li>Коли ви використовуєте функцію цитування, щоб відповісти на повідомлення на форумі, ви побачите, що текст повідомлення додано до вікна повідомлення, обгорнутий блоком <strong>[quote=&quot;&quot;][/quote]</strong>. Цей метод дозволяє цитувати з посиланням на особу чи будь-що інше, що ви оберете! Наприклад, щоб процитувати фрагмент тексту, написаний паном Блобі, ви б ввели:<br /><br /><strong>[quote=&quot;Пан Блобі&quot;]</strong>Текст, написаний паном Блобі, буде тут<strong>[/quote]</strong><br /><br />Результат автоматично додасть &quot;Пан Блобі написав(-ла):&quot; перед самим текстом. Пам’ятайте, вам <strong>обов’язково</strong> потрібно включати лапки &quot;&quot; навколо імені, яке ви цитуєте, вони не є необов’язковими.</li><li>Другий метод дозволяє цитувати щось без посилання на джерело. Щоб скористатися ним, обгорніть текст тегами <strong>[quote][/quote]</strong>. Під час перегляду повідомлення текст просто буде показано в блоці цитати.</li></ul>',
	'HELP_BBCODE_QUOTES_TEXT_QUESTION'	=> 'Цитування тексту у відповідях',

	'HELP_BBCODE_TEXT_BASIC_ANSWER'	=> 'BBCode містить теги, що дозволяють швидко змінити базовий стиль вашого тексту. Це досягається наступними способами: <ul><li>Щоб зробити фрагмент тексту жирним, обгорніть його <strong>[b][/b]</strong>, напр. <br /><br /><strong>[b]</strong>Привіт<strong>[/b]</strong><br /><br />стане <strong>Привіт</strong></li><li>Для підкреслення використовуйте <strong>[u][/u]</strong>, наприклад:<br /><br /><strong>[u]</strong>Доброго ранку<strong>[/u]</strong><br /><br />стає <span style="text-decoration: underline">Доброго ранку</span></li><li>Щоб зробити текст курсивом, використовуйте <strong>[i][/i]</strong>, напр.<br /><br />Це <strong>[i]</strong>Чудово!<strong>[/i]</strong><br /><br />дасть Це <i>Чудово!</i></li></ul>',
	'HELP_BBCODE_TEXT_BASIC_QUESTION'	=> 'Як створити жирний, курсивний і підкреслений текст',
	'HELP_BBCODE_TEXT_COLOR_ANSWER'	=> 'Щоб змінити колір або розмір вашого тексту, можна використовувати наступні теги. Майте на увазі, що вигляд результату залежить від браузера та системи глядача: <ul><li>Зміна кольору тексту досягається обгортанням його <strong>[color=][/color]</strong>. Ви можете вказати або розпізнану назву кольору (напр. red, blue, yellow тощо), або шістнадцяткове трійкове значення, напр. #FFFFFF, #000000. Наприклад, щоб створити червоний текст, ви могли б використати:<br /><br /><strong>[color=red]</strong>Привіт!<strong>[/color]</strong><br /><br />або<br /><br /><strong>[color=#FF0000]</strong>Привіт!<strong>[/color]</strong><br /><br />Обидва варіанти виведуть <span style="color:red">Привіт!</span></li><li>Зміна розміру тексту досягається подібним чином за допомогою <strong>[size=][/size]</strong>. Цей тег залежить від обраного користувачем шаблону, але рекомендований формат — числове значення, що представляє розмір тексту у відсотках, починаючи з 20 (дуже малий) до 200 (дуже великий) за замовчуванням. Наприклад:<br /><br /><strong>[size=30]</strong>МАЛИЙ<strong>[/size]</strong><br /><br />зазвичай буде <span style="font-size:30%;">МАЛИЙ</span><br /><br />тоді як:<br /><br /><strong>[size=200]</strong>ВЕЛИЧЕЗНИЙ!<strong>[/size]</strong><br /><br />буде <span style="font-size:200%;">ВЕЛИЧЕЗНИЙ!</span></li></ul>',
	'HELP_BBCODE_TEXT_COLOR_QUESTION'	=> 'Як змінити колір або розмір тексту',
	'HELP_BBCODE_TEXT_COMBINE_ANSWER'	=> 'Так, звичайно можете, наприклад, щоб привернути чиюсь увагу, ви могли б написати:<br /><br /><strong>[size=200][color=red][b]</strong>ПОДИВІТЬСЯ НА МЕНЕ!<strong>[/b][/color][/size]</strong><br /><br />це виведе <span style="color:red;font-size:200%;"><strong>ПОДИВІТЬСЯ НА МЕНЕ!</strong></span><br /><br />Втім, ми не рекомендуємо виводити багато тексту, що виглядає так! Пам’ятайте, саме на вас, авторі повідомлення, лежить відповідальність за правильне закриття тегів. Наприклад, наступне неправильно:<br /><br /><strong>[b][u]</strong>Це неправильно<strong>[/b][/u]</strong>',
	'HELP_BBCODE_TEXT_COMBINE_QUESTION'	=> 'Чи можу я поєднувати теги форматування?',
));
